// <auto-generated />
namespace VĐKO1721050102.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_tal_peopl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_tal_peopl));
        
        string IMigrationMetadata.Id
        {
            get { return "202110290307428_create_tal_peopl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
